LOCAL_PATH := $(call my-dir)

#
# Apk section
#

# PWN-Term (cert-debug)
include $(CLEAR_VARS)
LOCAL_MODULE := pwn-term
LOCAL_SRC_FILES := apps/$(LOCAL_MODULE).apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)

# PWN-X11 (cert-debug)
include $(CLEAR_VARS)
LOCAL_MODULE := pwn-x11
LOCAL_SRC_FILES := apps/$(LOCAL_MODULE).apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)
